stages:
  team:
    cmd: python python_files/teams_data.py
  players:
    cmd: python python_files/players_data.py
  ML:
    cmd: python python_files/ml.py
    params:
    - ML.seed
    - ML.split
    - ML.shuffle
    - ML.n_components
    metrics:
    - /project/MSIN0166_Data_Engineering_individual/scores.json
  data_transformation:
    cmd: python python_files/data_transformation.py
  write_into_database:
    cmd: python python_files/write_into_database.py